name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install dependencies
      uses: r-lib/actions/setup-r-dependencies@v2

    - name: Run R code and deploy
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git checkout -B gh-pages
        R -e "shinylive::export(appdir = 'myapp', destdir = 'docs')"
        git add docs
        git commit -m "Deploy to GitHub Pages"
        git push origin gh-pages -f
      shell: bash